

CREATE OR REPLACE VIEW SEPTEMBARSKI_RACUNI (NAZIVSLADOLEDA,IDSTAVKE,IDRACUNA,DATUMIZDAVANJARACUNA,VREMEIZDAVANJARACUNA,CENARACUNA,CENASVIHRACUNA)AS 
SELECT SL.NAZIVSLADOLEDA, ST.IDSTAVKE, R.IDRACUNA, R.DATUMIZDAVANJARACUNA , R.VREMEIZDAVANJARACUNA, R.CENARACUNA,
(SELECT SUM(CENARACUNA) FROM RACUN WHERE DATUMIZDAVANJARACUNA LIKE '%-SEP-%' ) 
FROM SLADOLED SL, STAVKA ST, RACUN R 
WHERE ST.SLADOLED_NAZIVSLADOLEDA = SL.NAZIVSLADOLEDA 
AND ST.RACUN_IDRACUNA = R.IDRACUNA 
AND R.DATUMIZDAVANJARACUNA LIKE '%-SEP-%' 
GROUP BY R.DATUMIZDAVANJARACUNA, R.VREMEIZDAVANJARACUNA, R.CENARACUNA, R.IDRACUNA, SL.NAZIVSLADOLEDA, ST.IDSTAVKE;


CREATE OR REPLACE VIEW OKTOBARSKI_RACUNI (NAZIVSLADOLEDA,IDSTAVKE,IDRACUNA,DATUMIZDAVANJARACUNA,VREMEIZDAVANJARACUNA,CENARACUNA,CENASVIHRACUNA)AS 
SELECT SL.NAZIVSLADOLEDA, ST.IDSTAVKE, R.IDRACUNA, R.DATUMIZDAVANJARACUNA , R.VREMEIZDAVANJARACUNA,  R.CENARACUNA,
(SELECT SUM(CENARACUNA) FROM RACUN WHERE DATUMIZDAVANJARACUNA LIKE '%-OCT-%' ) 
FROM SLADOLED SL, STAVKA ST, RACUN R 
WHERE ST.SLADOLED_NAZIVSLADOLEDA = SL.NAZIVSLADOLEDA 
AND ST.RACUN_IDRACUNA = R.IDRACUNA 
AND R.DATUMIZDAVANJARACUNA LIKE '%-OCT-%' 
GROUP BY R.DATUMIZDAVANJARACUNA, R.VREMEIZDAVANJARACUNA, R.CENARACUNA, R.IDRACUNA, SL.NAZIVSLADOLEDA, ST.IDSTAVKE;


CREATE OR REPLACE VIEW PREPODNEVNI_RACUNI (NAZIVSLADOLEDA,IDSTAVKE,IDRACUNA,DATUMIZDAVANJARACUNA,VREMEIZDAVANJARACUNA,CENARACUNA,PROSECNACENARACUNA)AS 
SELECT SL.NAZIVSLADOLEDA, ST.IDSTAVKE, R.IDRACUNA, R.DATUMIZDAVANJARACUNA , R.VREMEIZDAVANJARACUNA,  R.CENARACUNA, 
(SELECT AVG(CENARACUNA) FROM RACUN WHERE VREMEIZDAVANJARACUNA LIKE '% AM' )  
FROM SLADOLED SL, STAVKA ST, RACUN R 
WHERE ST.SLADOLED_NAZIVSLADOLEDA = SL.NAZIVSLADOLEDA 
AND ST.RACUN_IDRACUNA = R.IDRACUNA 
AND R.VREMEIZDAVANJARACUNA LIKE '% AM'  
GROUP BY R.DATUMIZDAVANJARACUNA, R.VREMEIZDAVANJARACUNA, R.CENARACUNA, R.IDRACUNA, SL.NAZIVSLADOLEDA, ST.IDSTAVKE;


CREATE OR REPLACE VIEW POSLEPODNEVNI_RACUNI (NAZIVSLADOLEDA,IDSTAVKE,IDRACUNA,DATUMIZDAVANJARACUNA,VREMEIZDAVANJARACUNA,CENARACUNA,PROSECNACENARACUNA)AS 
SELECT SL.NAZIVSLADOLEDA, ST.IDSTAVKE, R.IDRACUNA, R.DATUMIZDAVANJARACUNA , R.VREMEIZDAVANJARACUNA,  R.CENARACUNA,
(SELECT AVG(CENARACUNA) FROM RACUN WHERE VREMEIZDAVANJARACUNA LIKE '% PM') 
FROM SLADOLED SL, STAVKA ST, RACUN R 
WHERE ST.SLADOLED_NAZIVSLADOLEDA = SL.NAZIVSLADOLEDA 
AND ST.RACUN_IDRACUNA = R.IDRACUNA 
AND R.VREMEIZDAVANJARACUNA LIKE '% PM' 
GROUP BY R.DATUMIZDAVANJARACUNA, R.VREMEIZDAVANJARACUNA, R.CENARACUNA, R.IDRACUNA, SL.NAZIVSLADOLEDA, ST.IDSTAVKE;


